// Builds optimized portrait assets from the photo in the project root.
// portrait.png = background-removed portrait (transparent PNG, cropped head-to-waist).
// To swap the photo: remove its background (e.g. remove.bg), crop, save as portrait.png, run `npm run images`.
import sharp from 'sharp';
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

const OUT = 'public/assets';
mkdirSync(OUT, { recursive: true });

const cutout = await sharp('portrait.png').ensureAlpha().png().toBuffer();

// Content hash in the filename, so a new photo always gets a new URL (no stale browser caches).
const hash = createHash('sha1').update(readFileSync('portrait.png')).digest('hex').slice(0, 8);
for (const f of readdirSync(OUT)) if (/^portrait-.*\.webp$/.test(f)) rmSync(`${OUT}/${f}`);
const files = {};
for (const w of [720, 420]) {
  const name = `portrait-${hash}-${w}.webp`;
  const info = await sharp(cutout).resize({ width: w, withoutEnlargement: true }).webp({ quality: 86, alphaQuality: 90 }).toFile(`${OUT}/${name}`);
  files[w] = { src: `/assets/${name}`, width: info.width };
}
writeFileSync(
  'src/data/portraitAssets.ts',
  `// Generated by scripts/build-images.mjs — do not edit by hand.
export const portraitAssets = {
  large: '${files[720].src}',
  small: '${files[420].src}',
  srcSet: '${files[420].src} ${files[420].width}w, ${files[720].src} ${files[720].width}w',
};
`,
);
const html = readFileSync('index.html', 'utf8').replace(/href="\/assets\/portrait-[^"]+\.webp"/, `href="${files[720].src}"`);
writeFileSync('index.html', html);

// Social share image (1200x630) on a dark backdrop
const portrait = await sharp(cutout).resize({ height: 600 }).png().toBuffer();
await sharp({ create: { width: 1200, height: 630, channels: 4, background: '#07070a' } })
  .composite([
    {
      input: Buffer.from(`<svg width="1200" height="630" xmlns="http://www.w3.org/2000/svg">
        <defs><radialGradient id="g" cx="78%" cy="45%" r="45%"><stop offset="0" stop-color="#e5132b" stop-opacity="0.45"/><stop offset="1" stop-color="#e5132b" stop-opacity="0"/></radialGradient></defs>
        <rect width="1200" height="630" fill="url(#g)"/>
      </svg>`),
    },
    { input: portrait, gravity: 'southeast' },
    {
      input: Buffer.from(`<svg width="1200" height="630" xmlns="http://www.w3.org/2000/svg">
        <text x="72" y="300" font-family="Impact, 'Arial Narrow', sans-serif" font-size="128" fill="#f4f1ec" letter-spacing="4">SAHIL</text>
        <text x="78" y="352" font-family="Helvetica, Arial, sans-serif" font-weight="700" font-size="26" fill="#ff3d5a" letter-spacing="16">THE SERIES</text>
        <text x="78" y="420" font-family="Helvetica, Arial, sans-serif" font-weight="600" font-size="18" fill="#a7a6ad" letter-spacing="5">SOFTWARE ENGINEER • IIT GUWAHATI</text>
      </svg>`),
    },
  ])
  .jpeg({ quality: 85 })
  .toFile(`${OUT}/og-image.jpg`);
console.log('images built');
