// Generated by scripts/build-images.mjs — do not edit by hand.
export const portraitAssets = {
  large: '/assets/portrait-f728ad24-720.webp',
  small: '/assets/portrait-f728ad24-420.webp',
  srcSet: '/assets/portrait-f728ad24-420.webp 420w, /assets/portrait-f728ad24-720.webp 720w',
};
